version: '3.8'

services:
  # 1. Container do Banco de Dados
  sqlserver_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: meubanco_sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuaSenhaForte123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql # Isso garante que os dados não sumam se o container reiniciar!

  # 2. Container da sua Aplicação C#
  meu_app_csharp:
    build: . # Diz para o compose ler o Dockerfile que está nesta pasta
    container_name: app_restaurantes
    depends_on:
      - sqlserver_db # O app C# só liga depois que o banco ligar

volumes:
  sqlserver_data: